config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :movies do 
  	resources :movie_roles, as: :role, path: "roles"
  end
  resources :actors
end

app/models/actor.rb
class Actor < ApplicationRecord
	def role
		# Movie.where(:"role.actor_id"=> self.id)
		MovieRole.where(actor_id: self.id)
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :roles, class_name: 'MovieRole'
	# belongs_to :author, :class_name => 'User'
end

app/models/movie_role.rb
class MovieRole < ApplicationRecord
	belongs_to :actor  ,optional: true
	belongs_to :movie
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception

  protect_from_forgery with: :null_session
end

app/controllers/movie_roles_controller.rb
class MovieRolesController < ApplicationController
  before_action :set_movie
  before_action :set_movie_role, only: [:show, :edit, :update, :destroy]

  # GET /movie_roles
  # GET /movie_roles.json
  def index
    @movie_roles = @movie.roles
  end

  # GET /movie_roles/1
  # GET /movie_roles/1.json
  def show
  end

  # GET /movie_roles/new
  def new
    @movie_role = MovieRole.new
  end

  # GET /movie_roles/1/edit
  def edit
  end

  # POST /movie_roles
  # POST /movie_roles.json
  def create
    @movie_role = MovieRole.new(movie_role_params)

    respond_to do |format|
      if @movie_role.save
        format.html { redirect_to @movie_role, notice: 'Movie role was successfully created.' }
        format.json { render :show, status: :created, location: @movie_role }
      else
        format.html { render :new }
        format.json { render json: @movie_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movie_roles/1
  # PATCH/PUT /movie_roles/1.json
  def update
    respond_to do |format|
      if @movie_role.update(movie_role_params)
        format.html { redirect_to @movie_role, notice: 'Movie role was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie_role }
      else
        format.html { render :edit }
        format.json { render json: @movie_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movie_roles/1
  # DELETE /movie_roles/1.json
  def destroy
    @movie_role.destroy
    respond_to do |format|
      format.html { redirect_to movie_roles_url, notice: 'Movie role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie_role
      @movie_role = @movie.roles.find_by(:id => params[:id])
    end
    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_role_params
      params.require(:movie_role).permit(:character, :actor_id)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:id,:title)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movie_roles_helper.rb
module MovieRolesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/actors/_form.html.erb
<%= form_with(model: actor, local: true) do |form| %>
  <% if actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :actor_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Actors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.name %></td>
        <td><%= link_to 'Show', actor %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
        <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actor', new_actor_path %>

app/views/actors/new.html.erb
<h1>New Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @actor.name %>
</p>

<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Api</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movie_roles/_form.html.erb
<%= form_with(model: movie_role, local: true) do |form| %>
  <% if movie_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie_role.errors.count, "error") %> prohibited this movie_role from being saved:</h2>

      <ul>
      <% movie_role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :character %>
    <%= form.text_field :character, id: :movie_role_character %>
  </div>

  <div class="field">
    <%= form.label :actor_id %>
    <%= form.text_field :actor_id, id: :movie_role_actor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movie_roles/edit.html.erb
<h1>Editing Movie Role</h1>

<%= render 'form', movie_role: @movie_role %>

<%= link_to 'Show', @movie_role %> |
<%= link_to 'Back', movie_roles_path %>

app/views/movie_roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movie Roles</h1>

<table>
  <thead>
    <tr>
      <th>Character</th>
      <th>Actor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movie_roles.each do |movie_role| %>
      <tr>
        <td><%= movie_role.character %></td>
        <td><%= movie_role.actor_id %></td>
        <td><%= link_to 'Show', movie_role %></td>
        <td><%= link_to 'Edit', edit_movie_role_path(movie_role) %></td>
        <td><%= link_to 'Destroy', movie_role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie Role', new_movie_role_path %>

app/views/movie_roles/new.html.erb
<h1>New Movie Role</h1>

<%= render 'form', movie_role: @movie_role %>

<%= link_to 'Back', movie_roles_path %>

app/views/movie_roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Character:</strong>
  <%= @movie_role.character %>
</p>

<p>
  <strong>Actor:</strong>
  <%= @movie_role.actor_id %>
</p>

<%= link_to 'Edit', edit_movie_role_path(@movie_role) %> |
<%= link_to 'Back', movie_roles_path %>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :movie_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>